apiVersion: v1
kind: Service
metadata:
  name: backend-go
  namespace: default
  labels:
    app.kubernetes.io/name: backend-go
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: backend-go
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: grpc
      port: 50051
      targetPort: 50051
